// Simple visual transliteration: maps Latin letters to target script glyphs.
// Note: This is not linguistically accurate. It produces script-looking text
// similar to legacy fonts like Kruti-dev that remap ASCII codepoints.

const MAPS = {
  tamil: {
    a: 'அ',
    b: 'ஆ',
    c: 'இ',
    d: 'ஈ',
    e: 'உ',
    f: 'ஊ',
    g: 'எ',
    h: 'ஏ',
    i: 'ஐ',
    j: 'ஒ',
    k: 'ஓ',
    l: 'ஔ',
    m: 'க',
    n: 'ச',
    o: 'ட',
    p: 'த',
    q: 'ப',
    r: 'ர',
    s: 'ல',
    t: 'ள',
    u: 'ழ',
    v: 'வ',
    w: 'ஞ',
    x: 'ங',
    y: 'ண',
    z: 'ய',
    0: '௦',
    1: '௧',
    2: '௨',
    3: '௩',
    4: '௪',
    5: '௫',
    6: '௬',
    7: '௭',
    8: '௮',
    9: '௯',
    ' ': ' ',
    '.': '.',
    ',': ',',
    '!': '!',
    '?': '?',
    ':': ':',
    ';': ';',
    '-': '-',
    '(': '(',
    ')': ')'
  },
  hindi: {
    a: 'अ',
    b: 'ब',
    c: 'च',
    d: 'द',
    e: 'ए',
    f: 'फ',
    g: 'ग',
    h: 'ह',
    i: 'इ',
    j: 'ज',
    k: 'क',
    l: 'ल',
    m: 'म',
    n: 'न',
    o: 'ओ',
    p: 'प',
    q: 'क',
    r: 'र',
    s: 'स',
    t: 'त',
    u: 'उ',
    v: 'व',
    w: 'व',
    x: 'क्ष',
    y: 'य',
    z: 'ज़',
    0: '०',
    1: '१',
    2: '२',
    3: '३',
    4: '४',
    5: '५',
    6: '६',
    7: '७',
    8: '८',
    9: '९',
    ' ': ' ',
    '.': '।',
    ',': ',',
    '!': '!',
    '?': '?',
    ':': ':',
    ';': ';',
    '-': '-',
    '(': '(',
    ')': ')'
  },
  chinese: {
    a: '的',
    b: '一',
    c: '是',
    d: '在',
    e: '我',
    f: '有',
    g: '不',
    h: '这',
    i: '人',
    j: '他',
    k: '中',
    l: '大',
    m: '来',
    n: '上',
    o: '国',
    p: '个',
    q: '到',
    r: '说',
    s: '们',
    t: '为',
    u: '子',
    v: '而',
    w: '也',
    x: '小',
    y: '心',
    z: '见',
    0: '〇',
    1: '一',
    2: '二',
    3: '三',
    4: '四',
    5: '五',
    6: '六',
    7: '七',
    8: '八',
    9: '九',
    ' ': ' ',
    '.': '。',
    ',': '，',
    '!': '！',
    '?': '？',
    ':': '：',
    ';': '；',
    '-': '一',
    '(': '（',
    ')': '）'
  },
  arabic: {
    a: 'ا',
    b: 'ب',
    c: 'ج',
    d: 'د',
    e: 'ه',
    f: 'ف',
    g: 'غ',
    h: 'ح',
    i: 'ي',
    j: 'ج',
    k: 'ك',
    l: 'ل',
    m: 'م',
    n: 'ن',
    o: 'و',
    p: 'پ',
    q: 'ق',
    r: 'ر',
    s: 'س',
    t: 'ت',
    u: 'و',
    v: 'ڤ',
    w: 'و',
    x: 'خ',
    y: 'ي',
    z: 'ز',
    0: '٠',
    1: '١',
    2: '٢',
    3: '٣',
    4: '٤',
    5: '٥',
    6: '٦',
    7: '٧',
    8: '٨',
    9: '٩',
    ' ': ' ',
    '.': '۔',
    ',': '،',
    '!': '!',
    '?': '؟',
    ':': ':',
    ';': '؛',
    '-': '-',
    '(': '(',
    ')': ')'
  },
  japanese: {
    a: 'あ',
    b: 'べ',
    c: 'こ',
    d: 'だ',
    e: 'え',
    f: 'ふ',
    g: 'ぎ',
    h: 'ほ',
    i: 'い',
    j: 'じ',
    k: 'か',
    l: 'ら',
    m: 'ま',
    n: 'な',
    o: 'お',
    p: 'ぱ',
    q: 'く',
    r: 'ら',
    s: 'さ',
    t: 'た',
    u: 'う',
    v: 'ゔ',
    w: 'わ',
    x: 'くさ',
    y: 'や',
    z: 'ざ',
    0: '〇',
    1: '一',
    2: '二',
    3: '三',
    4: '四',
    5: '五',
    6: '六',
    7: '七',
    8: '八',
    9: '九',
    ' ': ' ',
    '.': '。',
    ',': '、',
    '!': '！',
    '?': '？',
    ':': '：',
    ';': '；',
    '-': 'ー',
    '(': '（',
    ')': '）'
  },
  korean: {
    a: '아',
    b: '브',
    c: '크',
    d: '드',
    e: '에',
    f: '프',
    g: '그',
    h: '흐',
    i: '이',
    j: '지',
    k: '크',
    l: '르',
    m: '므',
    n: '느',
    o: '오',
    p: '프',
    q: '쿠',
    r: '르',
    s: '스',
    t: '트',
    u: '우',
    v: '브',
    w: '우',
    x: '익스',
    y: '야',
    z: '즈',
    0: '〇',
    1: '일',
    2: '이',
    3: '삼',
    4: '사',
    5: '오',
    6: '육',
    7: '칠',
    8: '팔',
    9: '구',
    ' ': ' ',
    '.': '.',
    ',': ',',
    '!': '!',
    '?': '?',
    ':': ':',
    ';': ';',
    '-': '-',
    '(': '(',
    ')': ')'
  },
  cyrillic: {
    a: 'а',
    b: 'б',
    c: 'ц',
    d: 'д',
    e: 'е',
    f: 'ф',
    g: 'г',
    h: 'х',
    i: 'и',
    j: 'й',
    k: 'к',
    l: 'л',
    m: 'м',
    n: 'н',
    o: 'о',
    p: 'п',
    q: 'к',
    r: 'р',
    s: 'с',
    t: 'т',
    u: 'у',
    v: 'в',
    w: 'в',
    x: 'кс',
    y: 'ы',
    z: 'з',
    0: '0',
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '8',
    9: '9',
    ' ': ' ',
    '.': '.',
    ',': ',',
    '!': '!',
    '?': '?',
    ':': ':',
    ';': ';',
    '-': '-',
    '(': '(',
    ')': ')'
  }
};

function transliterate(text, lang) {
  const map = MAPS[lang];
  if (!map) return text;
  return text
    .split('')
    .map((ch) => {
      const lower = ch.toLowerCase();
      if (map[lower]) {
        // preserve case by using same glyph (scripts usually case-less)
        return map[lower];
      }
      return ch;
    })
    .join('');
}

function applyTransliterationToElement(el, lang) {
  const map = MAPS[lang];
  if (!map) return;
  // Walk text nodes to preserve <br/> and other markup
  const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT, null);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  for (const node of nodes) {
    node.nodeValue = transliterate(node.nodeValue, lang);
  }
}

function detectLangFromOptionLabel(label) {
  // Label examples: "Kavivanar (Tamil)", "Reem Kufi Ink (Arabic)"
  const match = label.match(/\(([^)]+)\)/);
  if (match) {
    const l = match[1].toLowerCase();
    if (l.includes('hindi')) return 'hindi';
    if (l.includes('tamil')) return 'tamil';
    if (l.includes('arabic')) return 'arabic';
    if (l.includes('chinese')) return 'chinese';
    if (l.includes('japanese')) return 'japanese';
    if (l.includes('korean')) return 'korean';
    if (l.includes('cyrillic')) return 'cyrillic';
  }
  // Fallback: try known font names
  const s = label.toLowerCase();
  if (s.includes('kalam') || s.includes('kruti-dev') || s.includes('kruti'))
    return 'hindi';
  if (s.includes('anek tamil') || s.includes('kavivanar')) return 'tamil';
  if (s.includes('reem kufi')) return 'arabic';
  if (s.includes('ma shan zheng')) return 'chinese';
  if (s.includes('yomogi')) return 'japanese';
  if (s.includes('nanum')) return 'korean';
  if (s.includes('marck script')) return 'cyrillic';
  return null;
}

export {
  transliterate,
  detectLangFromOptionLabel,
  applyTransliterationToElement
};
